# Warren host-tool compatibility ranges and last-known-good versions.
#
# Ranges are minimum-inclusive and maximum-exclusive. Exact versions record the
# environment that passed Warren's complete verification matrix; they do not
# claim that Homebrew can reproduce historical packages.

set(WARREN_BASELINE_CMAKE_MINIMUM "3.28.0")
set(WARREN_BASELINE_CMAKE_MAXIMUM "5.0.0")
set(WARREN_BASELINE_CMAKE_KNOWN_GOOD "4.2.3")

set(WARREN_BASELINE_NINJA_MINIMUM "1.13.0")
set(WARREN_BASELINE_NINJA_MAXIMUM "2.0.0")
set(WARREN_BASELINE_NINJA_KNOWN_GOOD "1.13.2")

set(WARREN_BASELINE_LLVM_MINIMUM "22.1.0")
set(WARREN_BASELINE_LLVM_MAXIMUM "23.0.0")
set(WARREN_BASELINE_LLVM_KNOWN_GOOD "22.1.8")

set(WARREN_BASELINE_LLD_MINIMUM "22.1.0")
set(WARREN_BASELINE_LLD_MAXIMUM "23.0.0")
set(WARREN_BASELINE_LLD_KNOWN_GOOD "22.1.8")

set(WARREN_BASELINE_QEMU_MINIMUM "11.0.0")
set(WARREN_BASELINE_QEMU_MAXIMUM "12.0.0")
set(WARREN_BASELINE_QEMU_KNOWN_GOOD "11.0.3")

set(WARREN_BASELINE_MTOOLS_MINIMUM "4.0.0")
set(WARREN_BASELINE_MTOOLS_MAXIMUM "5.0.0")
set(WARREN_BASELINE_MTOOLS_KNOWN_GOOD "4.0.49")

set(WARREN_BASELINE_PYTHON_MINIMUM "3.14.0")
set(WARREN_BASELINE_PYTHON_MAXIMUM "3.15.0")
set(WARREN_BASELINE_PYTHON_KNOWN_GOOD "3.14.6")
