# Warren freestanding AArch64 cross-toolchain.
#
# Machine-specific executable paths are generated by:
#   ./tools/bootstrap.sh --install

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(_warren_local_paths
    "${CMAKE_CURRENT_LIST_DIR}/../../.warren/ToolchainPaths.cmake"
)

if(NOT EXISTS "${_warren_local_paths}")
    message(FATAL_ERROR
        "Warren's local toolchain configuration is missing. "
        "Run ./tools/bootstrap.sh --install from the repository root."
    )
endif()

include("${_warren_local_paths}")

foreach(_required_path IN ITEMS
    WARREN_HOST_NINJA
    WARREN_CLANG
    WARREN_CLANGXX
    WARREN_LD_LLD
    WARREN_LLVM_AR
    WARREN_LLVM_OBJCOPY
    WARREN_LLVM_OBJDUMP
    WARREN_LLVM_READELF
    WARREN_QEMU_AARCH64
    WARREN_AARCH64_UEFI_CODE
)
    if(NOT EXISTS "${${_required_path}}")
        message(FATAL_ERROR
            "${_required_path} does not resolve to an existing path. "
            "Rerun ./tools/bootstrap.sh --install."
        )
    endif()
endforeach()

set(CMAKE_MAKE_PROGRAM "${WARREN_HOST_NINJA}" CACHE FILEPATH "Ninja" FORCE)

set(CMAKE_C_COMPILER "${WARREN_CLANG}")
set(CMAKE_CXX_COMPILER "${WARREN_CLANGXX}")
set(CMAKE_ASM_COMPILER "${WARREN_CLANG}")

set(CMAKE_C_COMPILER_TARGET aarch64-none-elf)
set(CMAKE_CXX_COMPILER_TARGET aarch64-none-elf)
set(CMAKE_ASM_COMPILER_TARGET aarch64-none-elf)

set(CMAKE_LINKER "${WARREN_LD_LLD}")
set(CMAKE_AR "${WARREN_LLVM_AR}")
set(CMAKE_C_COMPILER_AR "${WARREN_LLVM_AR}")
set(CMAKE_CXX_COMPILER_AR "${WARREN_LLVM_AR}")
set(CMAKE_OBJCOPY "${WARREN_LLVM_OBJCOPY}")
set(CMAKE_OBJDUMP "${WARREN_LLVM_OBJDUMP}")
set(CMAKE_READELF "${WARREN_LLVM_READELF}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

unset(_required_path)
unset(_warren_local_paths)
