#!/bin/sh

set -eu

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repository_root=$(CDPATH= cd -- "$script_dir/.." && pwd)
formula_manifest="$script_dir/dependencies/macos-brew.txt"
edk2_headers_script="$script_dir/dependencies/fetch_edk2_headers.sh"
firmware_manifest="$script_dir/dependencies/qemu-firmware.sha256"
toolchain_baseline="$script_dir/dependencies/ToolchainBaseline.cmake"
toolchain_version_checker="$script_dir/dependencies/check_tool_versions.cmake"
mode=check

say()
{
    printf '%s\n' "$*"
}

fail()
{
    printf 'bootstrap: error: %s\n' "$*" >&2
    exit 1
}

usage()
{
    say "Usage: ./tools/bootstrap.sh [--check | --install]"
    say ""
    say "  --check    Verify prerequisites without changing the machine (default)."
    say "  --install  Install missing Homebrew formulas, verify them, and write"
    say "             machine-local configuration under .warren/."
}

require_executable()
{
    executable_path=$1
    description=$2

    if [ ! -x "$executable_path" ]; then
        fail "$description was not found at $executable_path"
    fi
}

first_existing_file()
{
    for candidate_path in "$@"
    do
        if [ -f "$candidate_path" ]; then
            printf '%s\n' "$candidate_path"
            return 0
        fi
    done

    return 1
}

read_formulae()
{
    sed -e 's/[[:space:]]*#.*$//' -e '/^[[:space:]]*$/d' "$formula_manifest"
}

install_missing_formulae()
{
    missing_formulae=""
    installed_formulae=$(brew list --formula)

    for formula in $(read_formulae)
    do
        if ! printf '%s\n' "$installed_formulae" | grep -qx "$formula"; then
            missing_formulae="$missing_formulae $formula"
        fi
    done

    if [ -z "$missing_formulae" ]; then
        say "Homebrew dependencies: already installed"
        return
    fi

    if [ "$mode" = check ]; then
        fail "missing Homebrew formulae:$missing_formulae (run ./tools/bootstrap.sh --install)"
    fi

    say "Installing Homebrew formulae:$missing_formulae"
    # Formula names come only from the checked-in manifest and are intentionally
    # split into individual arguments here.
    brew install $missing_formulae
}

write_local_configuration()
{
    local_state_dir="$repository_root/.warren"
    mkdir -p "$local_state_dir"

    cmake_paths_tmp="$local_state_dir/ToolchainPaths.cmake.tmp"
    environment_tmp="$local_state_dir/environment.sh.tmp"
    report_tmp="$local_state_dir/toolchain-report.txt.tmp"

    {
        say "# Generated by tools/bootstrap.sh --install. Do not edit."
        printf 'set(WARREN_HOST_CMAKE "%s" CACHE FILEPATH "Host CMake executable")\n' "$cmake_path"
        printf 'set(WARREN_HOST_NINJA "%s" CACHE FILEPATH "Host Ninja executable")\n' "$ninja_path"
        printf 'set(WARREN_LLVM_ROOT "%s" CACHE PATH "Upstream LLVM installation")\n' "$llvm_root"
        printf 'set(WARREN_LLD_ROOT "%s" CACHE PATH "Upstream LLD installation")\n' "$lld_root"
        printf 'set(WARREN_LLD_LINK "%s" CACHE FILEPATH "Warren PE/COFF linker")\n' "$lld_link_path"
        printf 'set(WARREN_CLANG "%s" CACHE FILEPATH "Warren C compiler")\n' "$clang_path"
        printf 'set(WARREN_CLANGXX "%s" CACHE FILEPATH "Warren C++ compiler")\n' "$clangxx_path"
        printf 'set(WARREN_LD_LLD "%s" CACHE FILEPATH "Warren ELF linker")\n' "$ld_lld_path"
        printf 'set(WARREN_LLVM_AR "%s" CACHE FILEPATH "Warren archiver")\n' "$llvm_ar_path"
        printf 'set(WARREN_LLVM_OBJCOPY "%s" CACHE FILEPATH "Warren object converter")\n' "$llvm_objcopy_path"
        printf 'set(WARREN_LLVM_OBJDUMP "%s" CACHE FILEPATH "Warren object dumper")\n' "$llvm_objdump_path"
        printf 'set(WARREN_LLVM_READELF "%s" CACHE FILEPATH "Warren ELF inspector")\n' "$llvm_readelf_path"
        printf 'set(WARREN_LLVM_READOBJ "%s" CACHE FILEPATH "Warren object inspector")\n' "$llvm_readobj_path"
        printf 'set(WARREN_HOST_PYTHON "%s" CACHE FILEPATH "Host Python executable")\n' "$python_path"
        printf 'set(WARREN_MFORMAT "%s" CACHE FILEPATH "mtools FAT formatter")\n' "$mformat_path"
        printf 'set(WARREN_MMD "%s" CACHE FILEPATH "mtools directory creator")\n' "$mmd_path"
        printf 'set(WARREN_MCOPY "%s" CACHE FILEPATH "mtools file copier")\n' "$mcopy_path"
        printf 'set(WARREN_QEMU_AARCH64 "%s" CACHE FILEPATH "AArch64 QEMU system emulator")\n' "$qemu_path"
        printf 'set(WARREN_AARCH64_UEFI_CODE "%s" CACHE FILEPATH "AArch64 EDK2 firmware code image")\n' "$uefi_code_path"
        printf 'set(WARREN_AARCH64_UEFI_VARS "%s" CACHE FILEPATH "AArch64 EDK2 firmware variable template")\n' "$uefi_vars_path"
        printf 'set(WARREN_EDK2_ROOT "%s" CACHE PATH "Pinned local EDK2 header snapshot")\n' "$edk2_root"
        printf 'set(WARREN_EDK2_INCLUDE "%s" CACHE PATH "Pinned EDK2 MdePkg includes")\n' "$edk2_root/MdePkg/Include"
    } > "$cmake_paths_tmp"

    {
        say "# Generated by tools/bootstrap.sh --install. Source this file when needed."
        printf "export WARREN_LLVM_ROOT='%s'\n" "$llvm_root"
        printf "export WARREN_LLD_ROOT='%s'\n" "$lld_root"
        printf "export WARREN_QEMU_AARCH64='%s'\n" "$qemu_path"
        printf "export WARREN_AARCH64_UEFI_CODE='%s'\n" "$uefi_code_path"
        printf "export WARREN_AARCH64_UEFI_VARS='%s'\n" "$uefi_vars_path"
        printf "export WARREN_EDK2_ROOT='%s'\n" "$edk2_root"
        printf "export PATH='%s/bin:%s/bin':\"\$PATH\"\n" "$llvm_root" "$lld_root"
    } > "$environment_tmp"

    {
        say "Warren host toolchain report"
        say "Generated: $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
        say "Host: $(uname -s) $(uname -m)"
        say ""
        say "$("$cmake_path" --version | sed -n '1p')"
        say "ninja $($ninja_path --version)"
        say "$($clang_path --version | sed -n '1p')"
        say "$($ld_lld_path --version | sed -n '1p')"
        say "$($qemu_path --version | sed -n '1p')"
        say "$($mformat_path -V 2>&1 | sed -n '1p')"
        say "$($python_path --version 2>&1 | sed -n '1p')"
        say ""
        say "CMake: $cmake_path"
        say "Ninja: $ninja_path"
        say "LLVM: $llvm_root"
        say "LLD: $lld_root"
        say "LLVM symbolizer: $llvm_symbolizer_path"
        say "LLDB: $lldb_path"
        say "QEMU: $qemu_path"
        say "UEFI: $uefi_code_path"
        say "UEFI vars: $uefi_vars_path"
        say "UEFI code SHA-256: $(shasum -a 256 "$uefi_code_path" | awk '{ print $1 }')"
        say "UEFI vars SHA-256: $(shasum -a 256 "$uefi_vars_path" | awk '{ print $1 }')"
        say "EDK2 headers: $edk2_root"
        say "Compatibility baseline: $toolchain_baseline"
    } > "$report_tmp"

    mv "$cmake_paths_tmp" "$local_state_dir/ToolchainPaths.cmake"
    mv "$environment_tmp" "$local_state_dir/environment.sh"
    mv "$report_tmp" "$local_state_dir/toolchain-report.txt"
}

case "${1:-}" in
    ""|--check)
        mode=check
        ;;
    --install)
        mode=install
        ;;
    -h|--help)
        usage
        exit 0
        ;;
    *)
        usage >&2
        exit 2
        ;;
esac

if [ "$#" -gt 1 ]; then
    usage >&2
    exit 2
fi

[ "$(uname -s)" = Darwin ] || fail "the initial bootstrap supports macOS only"
[ -f "$formula_manifest" ] || fail "dependency manifest is missing: $formula_manifest"
[ -f "$firmware_manifest" ] || fail "QEMU firmware integrity manifest is missing: $firmware_manifest"
[ -f "$toolchain_baseline" ] || fail "toolchain compatibility baseline is missing: $toolchain_baseline"
[ -f "$toolchain_version_checker" ] || fail "toolchain version checker is missing: $toolchain_version_checker"
[ -x "$edk2_headers_script" ] || fail "EDK2 header acquisition script is missing or not executable"

command -v brew >/dev/null 2>&1 || fail "Homebrew is required for --check/--install; install it from https://brew.sh and rerun"

install_missing_formulae

brew_prefix=$(brew --prefix)
cmake_root=$(brew --prefix cmake)
ninja_root=$(brew --prefix ninja)
llvm_root=$(brew --prefix llvm)
lld_root=$(brew --prefix lld)
mtools_root=$(brew --prefix mtools)
python_root=$(brew --prefix python@3.14)
qemu_root=$(brew --prefix qemu)

cmake_path="$cmake_root/bin/cmake"
ninja_path="$ninja_root/bin/ninja"
clang_path="$llvm_root/bin/clang"
clangxx_path="$llvm_root/bin/clang++"
ld_lld_path="$lld_root/bin/ld.lld"
lld_link_path="$lld_root/bin/lld-link"
llvm_ar_path="$llvm_root/bin/llvm-ar"
llvm_objcopy_path="$llvm_root/bin/llvm-objcopy"
llvm_objdump_path="$llvm_root/bin/llvm-objdump"
llvm_readelf_path="$llvm_root/bin/llvm-readelf"
llvm_readobj_path="$llvm_root/bin/llvm-readobj"
llvm_symbolizer_path="$llvm_root/bin/llvm-symbolizer"
lldb_path="$llvm_root/bin/lldb"
python_path="$python_root/bin/python3.14"
mformat_path="$mtools_root/bin/mformat"
mmd_path="$mtools_root/bin/mmd"
mcopy_path="$mtools_root/bin/mcopy"
qemu_path="$qemu_root/bin/qemu-system-aarch64"

require_executable "$cmake_path" "CMake"
require_executable "$ninja_path" "Ninja"
require_executable "$clang_path" "upstream Clang"
require_executable "$clangxx_path" "upstream Clang++"
require_executable "$ld_lld_path" "LLD"
require_executable "$lld_link_path" "lld-link"
require_executable "$llvm_ar_path" "llvm-ar"
require_executable "$llvm_objcopy_path" "llvm-objcopy"
require_executable "$llvm_objdump_path" "llvm-objdump"
require_executable "$llvm_readelf_path" "llvm-readelf"
require_executable "$llvm_readobj_path" "llvm-readobj"
require_executable "$llvm_symbolizer_path" "llvm-symbolizer"
require_executable "$lldb_path" "LLDB"
require_executable "$python_path" "Python 3"
require_executable "$mformat_path" "mformat"
require_executable "$mmd_path" "mmd"
require_executable "$mcopy_path" "mcopy"
require_executable "$qemu_path" "qemu-system-aarch64"

cmake_version=$("$cmake_path" --version | sed -nE '1s/^cmake version ([0-9]+(\.[0-9]+)+).*$/\1/p')
ninja_version=$("$ninja_path" --version | sed -nE '1s/^([0-9]+(\.[0-9]+)+).*$/\1/p')
llvm_version=$("$clang_path" --version | sed -nE '1s/.*version ([0-9]+(\.[0-9]+)+).*$/\1/p')
lld_version=$("$ld_lld_path" --version | sed -nE '1s/.*LLD ([0-9]+(\.[0-9]+)+).*$/\1/p')
qemu_version=$("$qemu_path" --version | sed -nE '1s/.*version ([0-9]+(\.[0-9]+)+).*$/\1/p')
mtools_version=$("$mformat_path" -V 2>&1 | sed -nE '1s/.*mtools\) ([0-9]+(\.[0-9]+)+).*$/\1/p')
python_version=$("$python_path" --version 2>&1 | sed -nE '1s/^Python ([0-9]+(\.[0-9]+)+).*$/\1/p')

"$cmake_path" \
    -DWARREN_BASELINE_FILE="$toolchain_baseline" \
    -DWARREN_ACTUAL_CMAKE="$cmake_version" \
    -DWARREN_ACTUAL_NINJA="$ninja_version" \
    -DWARREN_ACTUAL_LLVM="$llvm_version" \
    -DWARREN_ACTUAL_LLD="$lld_version" \
    -DWARREN_ACTUAL_QEMU="$qemu_version" \
    -DWARREN_ACTUAL_MTOOLS="$mtools_version" \
    -DWARREN_ACTUAL_PYTHON="$python_version" \
    -P "$toolchain_version_checker"

uefi_code_path=$(first_existing_file \
    "$qemu_root/share/qemu/edk2-aarch64-code.fd" \
    "$brew_prefix/share/qemu/edk2-aarch64-code.fd" \
    "$qemu_root/share/qemu/edk2-arm-code.fd" \
    "$brew_prefix/share/qemu/edk2-arm-code.fd") || fail "QEMU's AArch64 EDK2 firmware image was not found"

uefi_vars_path=$(first_existing_file \
    "$qemu_root/share/qemu/edk2-arm-vars.fd" \
    "$brew_prefix/share/qemu/edk2-arm-vars.fd" \
    "$qemu_root/share/qemu/edk2-aarch64-vars.fd" \
    "$brew_prefix/share/qemu/edk2-aarch64-vars.fd") || fail "QEMU's AArch64 EDK2 variable-store template was not found"

uefi_firmware_directory=$(dirname "$uefi_code_path")
if [ "$uefi_firmware_directory" != "$(dirname "$uefi_vars_path")" ]; then
    fail "QEMU's UEFI code and variable images do not share one firmware directory"
fi
(cd "$uefi_firmware_directory" && shasum -a 256 -c "$firmware_manifest" >/dev/null) || \
    fail "QEMU firmware differs from the pinned integrity manifest"

if ! "$qemu_path" -machine help | grep -Eq '(^|[[:space:]])virt([[:space:]]|$)'; then
    fail "QEMU does not advertise the required AArch64 virt machine"
fi

probe_dir=$(mktemp -d "${TMPDIR:-/tmp}/warren-toolchain-probe.XXXXXX")
trap 'rm -rf "$probe_dir"' EXIT HUP INT TERM

printf '%s\n' \
    'extern "C" void warren_probe_entry() noexcept' \
    '{' \
    '    asm volatile("nop");' \
    '}' > "$probe_dir/probe.cpp"

"$clangxx_path" \
    --target=aarch64-none-elf \
    -std=c++20 \
    -ffreestanding \
    -fno-exceptions \
    -fno-rtti \
    -nostdlib \
    -Wall \
    -Wextra \
    -Werror \
    -c "$probe_dir/probe.cpp" \
    -o "$probe_dir/probe.o"

"$ld_lld_path" \
    -m aarch64elf \
    -e warren_probe_entry \
    -Ttext=0x40000000 \
    "$probe_dir/probe.o" \
    -o "$probe_dir/probe.elf"

"$llvm_readelf_path" -h "$probe_dir/probe.elf" | grep -q 'Machine:.*AArch64' || \
    fail "the linked probe is not an AArch64 ELF image"

"$llvm_objcopy_path" -O binary "$probe_dir/probe.elf" "$probe_dir/probe.bin"
[ -s "$probe_dir/probe.bin" ] || fail "llvm-objcopy produced an empty probe image"

say "Toolchain probe: AArch64 C++20 compile, ELF link, inspection, and conversion passed"
say "QEMU probe: AArch64 virt machine and UEFI firmware found"

if [ "$mode" = install ]; then
    "$edk2_headers_script" --install
else
    "$edk2_headers_script" --check
fi
edk2_root=$("$edk2_headers_script" --root)

if [ "$mode" = install ]; then
    write_local_configuration
    say "Local configuration: $repository_root/.warren/ToolchainPaths.cmake"
    say "Toolchain report: $repository_root/.warren/toolchain-report.txt"
fi

say "Bootstrap result: ready"
